version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.0
    steps:
      - checkout
      # Restore Cache
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
      # Install Node dependencies
      - run:
          name: Install local Dependencies
          command: npm install
      # Build Project
      - run:
          name: Build Server
          command: |
            npm run build:server
      - run:
          name: Build Client
          command: |
            npm run build:client
      # Cache local dependencies
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      # Cache the build folders for the deploy job
      - save_cache:
          key: build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - build
  deploy:
    working_directory: ~/repo
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      # build folder that needs to be deployed
      - restore_cache:
          key: build-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}
      # Add the build folder in github repo
      - run:
          name: Commit folder
          command: |
            git config credential.helper 'cache --timeout=120'
            git config --global user.email "e.tayyem@gmail.com"
            git config --global user.name "Eytyy"
            git add .
            git commit -m "added build folder from cache for deployment"
      # Install AWS cli
      - run:
          name: Install awscli
          command: |
            sudo pip install awsebcli --upgrade
      # Create AWS Credentials
      - run:
          name: Create AWS credentials manually
          command: |
            mkdir ~/.aws
            touch ~/.aws/config
            chmod 600 ~/.aws/config
            echo "[profile eb-cli]" > ~/.aws/config
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/config
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/config
            echo "region=us-west-2" >> ~/.aws/config
      - run:
          name: Deploy to AWS EB
          command: |
            eb use website-dev --profile eb-cli  
            eb deploy -v --staged --profile eb-cli

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - deploy:
          requires:
            - build
